package com.mengyirunian.entity;

import java.io.Serializable;

public class Jck implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jck.id
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jck.name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jck.simple_name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private String simpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jck.jk2016
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private Integer jk2016;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jck.jk2017
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private Integer jk2017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jck.ck2016
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private Integer ck2016;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_jck.ck2017
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private Integer ck2017;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jck.id
     *
     * @return the value of t_jck.id
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jck.id
     *
     * @param id the value for t_jck.id
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jck.name
     *
     * @return the value of t_jck.name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jck.name
     *
     * @param name the value for t_jck.name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jck.simple_name
     *
     * @return the value of t_jck.simple_name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jck.simple_name
     *
     * @param simpleName the value for t_jck.simple_name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName == null ? null : simpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jck.jk2016
     *
     * @return the value of t_jck.jk2016
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Integer getJk2016() {
        return jk2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jck.jk2016
     *
     * @param jk2016 the value for t_jck.jk2016
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setJk2016(Integer jk2016) {
        this.jk2016 = jk2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jck.jk2017
     *
     * @return the value of t_jck.jk2017
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Integer getJk2017() {
        return jk2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jck.jk2017
     *
     * @param jk2017 the value for t_jck.jk2017
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setJk2017(Integer jk2017) {
        this.jk2017 = jk2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jck.ck2016
     *
     * @return the value of t_jck.ck2016
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Integer getCk2016() {
        return ck2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jck.ck2016
     *
     * @param ck2016 the value for t_jck.ck2016
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setCk2016(Integer ck2016) {
        this.ck2016 = ck2016;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_jck.ck2017
     *
     * @return the value of t_jck.ck2017
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Integer getCk2017() {
        return ck2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_jck.ck2017
     *
     * @param ck2017 the value for t_jck.ck2017
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setCk2017(Integer ck2017) {
        this.ck2017 = ck2017;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", simpleName=").append(simpleName);
        sb.append(", jk2016=").append(jk2016);
        sb.append(", jk2017=").append(jk2017);
        sb.append(", ck2016=").append(ck2016);
        sb.append(", ck2017=").append(ck2017);
        sb.append("]");
        return sb.toString();
    }
}