package com.mengyirunian.entity;

import java.util.ArrayList;
import java.util.List;

public class JckCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public JckCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSimpleNameIsNull() {
            addCriterion("simple_name is null");
            return (Criteria) this;
        }

        public Criteria andSimpleNameIsNotNull() {
            addCriterion("simple_name is not null");
            return (Criteria) this;
        }

        public Criteria andSimpleNameEqualTo(String value) {
            addCriterion("simple_name =", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameNotEqualTo(String value) {
            addCriterion("simple_name <>", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameGreaterThan(String value) {
            addCriterion("simple_name >", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameGreaterThanOrEqualTo(String value) {
            addCriterion("simple_name >=", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameLessThan(String value) {
            addCriterion("simple_name <", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameLessThanOrEqualTo(String value) {
            addCriterion("simple_name <=", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameLike(String value) {
            addCriterion("simple_name like", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameNotLike(String value) {
            addCriterion("simple_name not like", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameIn(List<String> values) {
            addCriterion("simple_name in", values, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameNotIn(List<String> values) {
            addCriterion("simple_name not in", values, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameBetween(String value1, String value2) {
            addCriterion("simple_name between", value1, value2, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameNotBetween(String value1, String value2) {
            addCriterion("simple_name not between", value1, value2, "simpleName");
            return (Criteria) this;
        }

        public Criteria andJk2016IsNull() {
            addCriterion("jk2016 is null");
            return (Criteria) this;
        }

        public Criteria andJk2016IsNotNull() {
            addCriterion("jk2016 is not null");
            return (Criteria) this;
        }

        public Criteria andJk2016EqualTo(Integer value) {
            addCriterion("jk2016 =", value, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016NotEqualTo(Integer value) {
            addCriterion("jk2016 <>", value, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016GreaterThan(Integer value) {
            addCriterion("jk2016 >", value, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016GreaterThanOrEqualTo(Integer value) {
            addCriterion("jk2016 >=", value, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016LessThan(Integer value) {
            addCriterion("jk2016 <", value, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016LessThanOrEqualTo(Integer value) {
            addCriterion("jk2016 <=", value, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016In(List<Integer> values) {
            addCriterion("jk2016 in", values, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016NotIn(List<Integer> values) {
            addCriterion("jk2016 not in", values, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016Between(Integer value1, Integer value2) {
            addCriterion("jk2016 between", value1, value2, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2016NotBetween(Integer value1, Integer value2) {
            addCriterion("jk2016 not between", value1, value2, "jk2016");
            return (Criteria) this;
        }

        public Criteria andJk2017IsNull() {
            addCriterion("jk2017 is null");
            return (Criteria) this;
        }

        public Criteria andJk2017IsNotNull() {
            addCriterion("jk2017 is not null");
            return (Criteria) this;
        }

        public Criteria andJk2017EqualTo(Integer value) {
            addCriterion("jk2017 =", value, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017NotEqualTo(Integer value) {
            addCriterion("jk2017 <>", value, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017GreaterThan(Integer value) {
            addCriterion("jk2017 >", value, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017GreaterThanOrEqualTo(Integer value) {
            addCriterion("jk2017 >=", value, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017LessThan(Integer value) {
            addCriterion("jk2017 <", value, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017LessThanOrEqualTo(Integer value) {
            addCriterion("jk2017 <=", value, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017In(List<Integer> values) {
            addCriterion("jk2017 in", values, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017NotIn(List<Integer> values) {
            addCriterion("jk2017 not in", values, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017Between(Integer value1, Integer value2) {
            addCriterion("jk2017 between", value1, value2, "jk2017");
            return (Criteria) this;
        }

        public Criteria andJk2017NotBetween(Integer value1, Integer value2) {
            addCriterion("jk2017 not between", value1, value2, "jk2017");
            return (Criteria) this;
        }

        public Criteria andCk2016IsNull() {
            addCriterion("ck2016 is null");
            return (Criteria) this;
        }

        public Criteria andCk2016IsNotNull() {
            addCriterion("ck2016 is not null");
            return (Criteria) this;
        }

        public Criteria andCk2016EqualTo(Integer value) {
            addCriterion("ck2016 =", value, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016NotEqualTo(Integer value) {
            addCriterion("ck2016 <>", value, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016GreaterThan(Integer value) {
            addCriterion("ck2016 >", value, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016GreaterThanOrEqualTo(Integer value) {
            addCriterion("ck2016 >=", value, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016LessThan(Integer value) {
            addCriterion("ck2016 <", value, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016LessThanOrEqualTo(Integer value) {
            addCriterion("ck2016 <=", value, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016In(List<Integer> values) {
            addCriterion("ck2016 in", values, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016NotIn(List<Integer> values) {
            addCriterion("ck2016 not in", values, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016Between(Integer value1, Integer value2) {
            addCriterion("ck2016 between", value1, value2, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2016NotBetween(Integer value1, Integer value2) {
            addCriterion("ck2016 not between", value1, value2, "ck2016");
            return (Criteria) this;
        }

        public Criteria andCk2017IsNull() {
            addCriterion("ck2017 is null");
            return (Criteria) this;
        }

        public Criteria andCk2017IsNotNull() {
            addCriterion("ck2017 is not null");
            return (Criteria) this;
        }

        public Criteria andCk2017EqualTo(Integer value) {
            addCriterion("ck2017 =", value, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017NotEqualTo(Integer value) {
            addCriterion("ck2017 <>", value, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017GreaterThan(Integer value) {
            addCriterion("ck2017 >", value, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017GreaterThanOrEqualTo(Integer value) {
            addCriterion("ck2017 >=", value, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017LessThan(Integer value) {
            addCriterion("ck2017 <", value, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017LessThanOrEqualTo(Integer value) {
            addCriterion("ck2017 <=", value, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017In(List<Integer> values) {
            addCriterion("ck2017 in", values, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017NotIn(List<Integer> values) {
            addCriterion("ck2017 not in", values, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017Between(Integer value1, Integer value2) {
            addCriterion("ck2017 between", value1, value2, "ck2017");
            return (Criteria) this;
        }

        public Criteria andCk2017NotBetween(Integer value1, Integer value2) {
            addCriterion("ck2017 not between", value1, value2, "ck2017");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jck
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 14 13:11:05 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}