package com.mengyirunian.entity;

import java.io.Serializable;

public class Kjlx implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_kjlx.id
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_kjlx.name
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_kjlx.simple_name
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    private String simpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_kjlx.kjlx
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    private String kjlx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_kjlx
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_kjlx.id
     *
     * @return the value of t_kjlx.id
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_kjlx.id
     *
     * @param id the value for t_kjlx.id
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_kjlx.name
     *
     * @return the value of t_kjlx.name
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_kjlx.name
     *
     * @param name the value for t_kjlx.name
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_kjlx.simple_name
     *
     * @return the value of t_kjlx.simple_name
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_kjlx.simple_name
     *
     * @param simpleName the value for t_kjlx.simple_name
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName == null ? null : simpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_kjlx.kjlx
     *
     * @return the value of t_kjlx.kjlx
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    public String getKjlx() {
        return kjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_kjlx.kjlx
     *
     * @param kjlx the value for t_kjlx.kjlx
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    public void setKjlx(String kjlx) {
        this.kjlx = kjlx == null ? null : kjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kjlx
     *
     * @mbggenerated Sat Apr 21 01:29:45 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", simpleName=").append(simpleName);
        sb.append(", kjlx=").append(kjlx);
        sb.append("]");
        return sb.toString();
    }
}