package com.mengyirunian.entity;

import java.io.Serializable;

public class Nylt implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nylt.id
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nylt.name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nylt.simple_name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private String simpleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_nylt.nylt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private Integer nylt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_nylt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nylt.id
     *
     * @return the value of t_nylt.id
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nylt.id
     *
     * @param id the value for t_nylt.id
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nylt.name
     *
     * @return the value of t_nylt.name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nylt.name
     *
     * @param name the value for t_nylt.name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nylt.simple_name
     *
     * @return the value of t_nylt.simple_name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public String getSimpleName() {
        return simpleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nylt.simple_name
     *
     * @param simpleName the value for t_nylt.simple_name
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setSimpleName(String simpleName) {
        this.simpleName = simpleName == null ? null : simpleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_nylt.nylt
     *
     * @return the value of t_nylt.nylt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public Integer getNylt() {
        return nylt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_nylt.nylt
     *
     * @param nylt the value for t_nylt.nylt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    public void setNylt(Integer nylt) {
        this.nylt = nylt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_nylt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", simpleName=").append(simpleName);
        sb.append(", nylt=").append(nylt);
        sb.append("]");
        return sb.toString();
    }
}