package com.mengyirunian.entity;

import java.io.Serializable;

public class WeixinInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_weixin_info.id
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_weixin_info.key_name
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    private String keyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_weixin_info.value_name
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    private String valueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_weixin_info.id
     *
     * @return the value of t_weixin_info.id
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_weixin_info.id
     *
     * @param id the value for t_weixin_info.id
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_weixin_info.key_name
     *
     * @return the value of t_weixin_info.key_name
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    public String getKeyName() {
        return keyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_weixin_info.key_name
     *
     * @param keyName the value for t_weixin_info.key_name
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    public void setKeyName(String keyName) {
        this.keyName = keyName == null ? null : keyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_weixin_info.value_name
     *
     * @return the value of t_weixin_info.value_name
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    public String getValueName() {
        return valueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_weixin_info.value_name
     *
     * @param valueName the value for t_weixin_info.value_name
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    public void setValueName(String valueName) {
        this.valueName = valueName == null ? null : valueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", keyName=").append(keyName);
        sb.append(", valueName=").append(valueName);
        sb.append("]");
        return sb.toString();
    }
}