package com.mengyirunian.mapper;

import com.mengyirunian.entity.Gxjs;
import com.mengyirunian.entity.GxjsCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface GxjsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=GxjsSqlProvider.class, method="countByExample")
    int countByExample(GxjsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @DeleteProvider(type=GxjsSqlProvider.class, method="deleteByExample")
    int deleteByExample(GxjsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Delete({
        "delete from t_gxjs",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Insert({
        "insert into t_gxjs (name, simple_name, ",
        "gxjs)",
        "values (#{name,jdbcType=VARCHAR}, #{simpleName,jdbcType=VARCHAR}, ",
        "#{gxjs,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Gxjs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @InsertProvider(type=GxjsSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Gxjs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=GxjsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gxjs", property="gxjs", jdbcType=JdbcType.INTEGER)
    })
    List<Gxjs> selectByExampleWithRowbounds(GxjsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=GxjsSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gxjs", property="gxjs", jdbcType=JdbcType.INTEGER)
    })
    List<Gxjs> selectByExample(GxjsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Select({
        "select",
        "id, name, simple_name, gxjs",
        "from t_gxjs",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="gxjs", property="gxjs", jdbcType=JdbcType.INTEGER)
    })
    Gxjs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=GxjsSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Gxjs record, @Param("example") GxjsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=GxjsSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Gxjs record, @Param("example") GxjsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=GxjsSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Gxjs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_gxjs
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Update({
        "update t_gxjs",
        "set name = #{name,jdbcType=VARCHAR},",
          "simple_name = #{simpleName,jdbcType=VARCHAR},",
          "gxjs = #{gxjs,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Gxjs record);
}