package com.mengyirunian.mapper;

import com.mengyirunian.entity.Jck;
import com.mengyirunian.entity.JckCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface JckMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JckSqlProvider.class, method="countByExample")
    int countByExample(JckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @DeleteProvider(type=JckSqlProvider.class, method="deleteByExample")
    int deleteByExample(JckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Delete({
        "delete from t_jck",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Insert({
        "insert into t_jck (name, simple_name, ",
        "jk2016, jk2017, ",
        "ck2016, ck2017)",
        "values (#{name,jdbcType=VARCHAR}, #{simpleName,jdbcType=VARCHAR}, ",
        "#{jk2016,jdbcType=INTEGER}, #{jk2017,jdbcType=INTEGER}, ",
        "#{ck2016,jdbcType=INTEGER}, #{ck2017,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Jck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @InsertProvider(type=JckSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Jck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JckSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="jk2016", property="jk2016", jdbcType=JdbcType.INTEGER),
        @Result(column="jk2017", property="jk2017", jdbcType=JdbcType.INTEGER),
        @Result(column="ck2016", property="ck2016", jdbcType=JdbcType.INTEGER),
        @Result(column="ck2017", property="ck2017", jdbcType=JdbcType.INTEGER)
    })
    List<Jck> selectByExampleWithRowbounds(JckCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JckSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="jk2016", property="jk2016", jdbcType=JdbcType.INTEGER),
        @Result(column="jk2017", property="jk2017", jdbcType=JdbcType.INTEGER),
        @Result(column="ck2016", property="ck2016", jdbcType=JdbcType.INTEGER),
        @Result(column="ck2017", property="ck2017", jdbcType=JdbcType.INTEGER)
    })
    List<Jck> selectByExample(JckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Select({
        "select",
        "id, name, simple_name, jk2016, jk2017, ck2016, ck2017",
        "from t_jck",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="jk2016", property="jk2016", jdbcType=JdbcType.INTEGER),
        @Result(column="jk2017", property="jk2017", jdbcType=JdbcType.INTEGER),
        @Result(column="ck2016", property="ck2016", jdbcType=JdbcType.INTEGER),
        @Result(column="ck2017", property="ck2017", jdbcType=JdbcType.INTEGER)
    })
    Jck selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JckSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Jck record, @Param("example") JckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JckSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Jck record, @Param("example") JckCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JckSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Jck record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jck
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Update({
        "update t_jck",
        "set name = #{name,jdbcType=VARCHAR},",
          "simple_name = #{simpleName,jdbcType=VARCHAR},",
          "jk2016 = #{jk2016,jdbcType=INTEGER},",
          "jk2017 = #{jk2017,jdbcType=INTEGER},",
          "ck2016 = #{ck2016,jdbcType=INTEGER},",
          "ck2017 = #{ck2017,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Jck record);
}