package com.mengyirunian.mapper;

import com.mengyirunian.entity.Jrsx;
import com.mengyirunian.entity.JrsxCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface JrsxMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JrsxSqlProvider.class, method="countByExample")
    int countByExample(JrsxCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @DeleteProvider(type=JrsxSqlProvider.class, method="deleteByExample")
    int deleteByExample(JrsxCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Delete({
        "delete from t_jrsx",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Insert({
        "insert into t_jrsx (name, simple_name, ",
        "jrsx)",
        "values (#{name,jdbcType=VARCHAR}, #{simpleName,jdbcType=VARCHAR}, ",
        "#{jrsx,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Jrsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @InsertProvider(type=JrsxSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Jrsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JrsxSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="jrsx", property="jrsx", jdbcType=JdbcType.VARCHAR)
    })
    List<Jrsx> selectByExampleWithRowbounds(JrsxCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JrsxSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="jrsx", property="jrsx", jdbcType=JdbcType.VARCHAR)
    })
    List<Jrsx> selectByExample(JrsxCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Select({
        "select",
        "id, name, simple_name, jrsx",
        "from t_jrsx",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="jrsx", property="jrsx", jdbcType=JdbcType.VARCHAR)
    })
    Jrsx selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JrsxSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Jrsx record, @Param("example") JrsxCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JrsxSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Jrsx record, @Param("example") JrsxCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JrsxSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Jrsx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jrsx
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Update({
        "update t_jrsx",
        "set name = #{name,jdbcType=VARCHAR},",
          "simple_name = #{simpleName,jdbcType=VARCHAR},",
          "jrsx = #{jrsx,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Jrsx record);
}