package com.mengyirunian.mapper;

import com.mengyirunian.entity.Jstb;
import com.mengyirunian.entity.JstbCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface JstbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JstbSqlProvider.class, method="countByExample")
    int countByExample(JstbCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @DeleteProvider(type=JstbSqlProvider.class, method="deleteByExample")
    int deleteByExample(JstbCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Delete({
        "delete from t_jstb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Insert({
        "insert into t_jstb (name, simple_name, ",
        "amount)",
        "values (#{name,jdbcType=VARCHAR}, #{simpleName,jdbcType=VARCHAR}, ",
        "#{amount,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Jstb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @InsertProvider(type=JstbSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Jstb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JstbSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.INTEGER)
    })
    List<Jstb> selectByExampleWithRowbounds(JstbCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=JstbSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.INTEGER)
    })
    List<Jstb> selectByExample(JstbCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Select({
        "select",
        "id, name, simple_name, amount",
        "from t_jstb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.INTEGER)
    })
    Jstb selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JstbSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Jstb record, @Param("example") JstbCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JstbSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Jstb record, @Param("example") JstbCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=JstbSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Jstb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_jstb
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Update({
        "update t_jstb",
        "set name = #{name,jdbcType=VARCHAR},",
          "simple_name = #{simpleName,jdbcType=VARCHAR},",
          "amount = #{amount,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Jstb record);
}