package com.mengyirunian.mapper;

import com.mengyirunian.entity.Skd;
import com.mengyirunian.entity.SkdCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface SkdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=SkdSqlProvider.class, method="countByExample")
    int countByExample(SkdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @DeleteProvider(type=SkdSqlProvider.class, method="deleteByExample")
    int deleteByExample(SkdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Delete({
        "delete from t_skd",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Insert({
        "insert into t_skd (name, simple_name, ",
        "skd)",
        "values (#{name,jdbcType=VARCHAR}, #{simpleName,jdbcType=VARCHAR}, ",
        "#{skd,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Skd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @InsertProvider(type=SkdSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Skd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=SkdSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="skd", property="skd", jdbcType=JdbcType.INTEGER)
    })
    List<Skd> selectByExampleWithRowbounds(SkdCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=SkdSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="skd", property="skd", jdbcType=JdbcType.INTEGER)
    })
    List<Skd> selectByExample(SkdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Select({
        "select",
        "id, name, simple_name, skd",
        "from t_skd",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="skd", property="skd", jdbcType=JdbcType.INTEGER)
    })
    Skd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=SkdSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Skd record, @Param("example") SkdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=SkdSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Skd record, @Param("example") SkdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=SkdSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Skd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Update({
        "update t_skd",
        "set name = #{name,jdbcType=VARCHAR},",
          "simple_name = #{simpleName,jdbcType=VARCHAR},",
          "skd = #{skd,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Skd record);
}