package com.mengyirunian.mapper;

import com.mengyirunian.entity.WeixinInfo;
import com.mengyirunian.entity.WeixinInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface WeixinInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @SelectProvider(type=WeixinInfoSqlProvider.class, method="countByExample")
    int countByExample(WeixinInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @DeleteProvider(type=WeixinInfoSqlProvider.class, method="deleteByExample")
    int deleteByExample(WeixinInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @Delete({
        "delete from t_weixin_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @Insert({
        "insert into t_weixin_info (key_name, value_name)",
        "values (#{keyName,jdbcType=VARCHAR}, #{valueName,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(WeixinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @InsertProvider(type=WeixinInfoSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(WeixinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @SelectProvider(type=WeixinInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="key_name", property="keyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="value_name", property="valueName", jdbcType=JdbcType.VARCHAR)
    })
    List<WeixinInfo> selectByExampleWithRowbounds(WeixinInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @SelectProvider(type=WeixinInfoSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="key_name", property="keyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="value_name", property="valueName", jdbcType=JdbcType.VARCHAR)
    })
    List<WeixinInfo> selectByExample(WeixinInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @Select({
        "select",
        "id, key_name, value_name",
        "from t_weixin_info",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="key_name", property="keyName", jdbcType=JdbcType.VARCHAR),
        @Result(column="value_name", property="valueName", jdbcType=JdbcType.VARCHAR)
    })
    WeixinInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @UpdateProvider(type=WeixinInfoSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") WeixinInfo record, @Param("example") WeixinInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @UpdateProvider(type=WeixinInfoSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") WeixinInfo record, @Param("example") WeixinInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @UpdateProvider(type=WeixinInfoSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(WeixinInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_weixin_info
     *
     * @mbggenerated Sun Apr 15 09:18:02 CST 2018
     */
    @Update({
        "update t_weixin_info",
        "set key_name = #{keyName,jdbcType=VARCHAR},",
          "value_name = #{valueName,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(WeixinInfo record);
}