package com.mengyirunian.mapper;

import com.mengyirunian.entity.Zdt;
import com.mengyirunian.entity.ZdtCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface ZdtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=ZdtSqlProvider.class, method="countByExample")
    int countByExample(ZdtCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @DeleteProvider(type=ZdtSqlProvider.class, method="deleteByExample")
    int deleteByExample(ZdtCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Delete({
        "delete from t_zdt",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Insert({
        "insert into t_zdt (name, simple_name, ",
        "amount)",
        "values (#{name,jdbcType=VARCHAR}, #{simpleName,jdbcType=VARCHAR}, ",
        "#{amount,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Zdt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @InsertProvider(type=ZdtSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Zdt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=ZdtSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.VARCHAR)
    })
    List<Zdt> selectByExampleWithRowbounds(ZdtCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=ZdtSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.VARCHAR)
    })
    List<Zdt> selectByExample(ZdtCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Select({
        "select",
        "id, name, simple_name, amount",
        "from t_zdt",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="amount", property="amount", jdbcType=JdbcType.VARCHAR)
    })
    Zdt selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=ZdtSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Zdt record, @Param("example") ZdtCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=ZdtSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Zdt record, @Param("example") ZdtCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=ZdtSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Zdt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zdt
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Update({
        "update t_zdt",
        "set name = #{name,jdbcType=VARCHAR},",
          "simple_name = #{simpleName,jdbcType=VARCHAR},",
          "amount = #{amount,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Zdt record);
}