package com.mengyirunian.mapper;

import com.mengyirunian.entity.Zhd;
import com.mengyirunian.entity.ZhdCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.session.RowBounds;
import org.apache.ibatis.type.JdbcType;

public interface ZhdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=ZhdSqlProvider.class, method="countByExample")
    int countByExample(ZhdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @DeleteProvider(type=ZhdSqlProvider.class, method="deleteByExample")
    int deleteByExample(ZhdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Delete({
        "delete from t_zhd",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Insert({
        "insert into t_zhd (name, simple_name, ",
        "zhd)",
        "values (#{name,jdbcType=VARCHAR}, #{simpleName,jdbcType=VARCHAR}, ",
        "#{zhd,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(Zhd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @InsertProvider(type=ZhdSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(Zhd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=ZhdSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="zhd", property="zhd", jdbcType=JdbcType.INTEGER)
    })
    List<Zhd> selectByExampleWithRowbounds(ZhdCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @SelectProvider(type=ZhdSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="zhd", property="zhd", jdbcType=JdbcType.INTEGER)
    })
    List<Zhd> selectByExample(ZhdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Select({
        "select",
        "id, name, simple_name, zhd",
        "from t_zhd",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="simple_name", property="simpleName", jdbcType=JdbcType.VARCHAR),
        @Result(column="zhd", property="zhd", jdbcType=JdbcType.INTEGER)
    })
    Zhd selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=ZhdSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Zhd record, @Param("example") ZhdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=ZhdSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Zhd record, @Param("example") ZhdCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @UpdateProvider(type=ZhdSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Zhd record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_zhd
     *
     * @mbggenerated Sat Apr 14 13:11:05 CST 2018
     */
    @Update({
        "update t_zhd",
        "set name = #{name,jdbcType=VARCHAR},",
          "simple_name = #{simpleName,jdbcType=VARCHAR},",
          "zhd = #{zhd,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Zhd record);
}